name: mqtt-client
version: 1.0.1
summary: MQTT client for Sixgill Sense 2.0
description: Subscribes to MQTT topics, then sends received data to Sense 2.0
confinement: devmode

apps:
  mqtt-client:
    command: ./mqtt-client
    daemon: simple

parts:
  mqtt-client:
    plugin: dump
    source: .
    stage:
      - mqtt-client
      - mqtt-client-conf.json
